name: nog5
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - beautifulsoup4>=4.10.0,<5
  - biopython>=1.78,<2
  - cd-hit>=4.8.1,<5
  - click>=7.1.2,<9
  - cudatoolkit=11.3  # find your compatible CUDA versions using nvcc/nvidia-smi
  - h5py>=3.6.0,<4
  - matplotlib>=3.4.1,<4
  - numpy>=1.20.2,<2
  - openpyxl>=3.0.9,<4
  - optuna>=2.8.0,<3
  - pandas>=1.2.3,<2
  - pip>=21.0.1
  - pytest>=6.2.2,<7
  - python>=3.8.8,<12
  - pytorch::pytorch>=1.10.0,<2
  - pytorch::torchvision>=0.9.0,<1
  - pyyaml>=5.4.1,<7
  - scikit-learn>=0.24.2,<1
  - scipy>=1.6.2,<2
  - setuptools>=49.6.0,<59.6.0  # some bug in 59.6.0
  - tensorboard>=1.15,<3
  - tqdm>=4.59.0
  - typing-extensions>=3.7.4.3,<5
  - untangle>=1.1.1,<2
  - pip:
    - fair-esm>=0.4.0,<1
#    - nog5
#    - glyc_processing
#    - nsp3
